version: '3.4'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db    
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql   
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    image: elivando/node:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command:  'node index.js'
    volumes:
      - ./node:/usr/src/app
    tty: true
    build:
      context: node
      dockerfile: ./Dockerfile
    networks:
      - node-network
    ports:
      - 3000:3000

  nginx:
    image: elivando/nginx:prod
    container_name: nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    networks:
      - node-network
    ports:
      - 8080:80
   
networks: 
  node-network:
    driver: bridge